### ISSUE TITLE
Implement test class BankPersistenceTest

### ISSUE THREAD

**Issue by rgcv** [rgcv/es1617-adventures#41]
<a href="https://github.com/Squill3x"><img src="https://avatars1.githubusercontent.com/u/22553551?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Squill3x](https://github.com/Squill3x)**
_Monday Apr 03, 2017 at 09:59 GMT_
_Originally opened as https://github.com/tecnico-softeng/es17al_01-project/issues/41_

----

Dependencies:

1. **Bank**

- [x] #51: Make Bank class persistent
- [x] #39: Make Bank's fields persistent
- [x] #42: Implement relation between DomainRoot and Bank

2. **Client**

- [x] #53: Make Client class persistent
- [x] #64: Make Client's fields persistent
- [x] #60: Implement relation between Bank and Client

3. **Account**

- [x] #43: Make Account class persistent
- [x] #40: Make Account's fields persistent
- [x] #59: Implement relation between Bank and Account
- [x] #62: Implement relation between Account and Client

4. **Operation**

- [x] #54: Make Operation class persistent
- [x] #65: Make Operation's fields persistent
- [x] #61: Implement relation between Bank and Operation
- [x] #63: Implement relation between Operation and Account

Various commits should be associated with this issue, one per "persistence advancement"
