### ISSUE TITLE
Implement test class HotelPersistenceTest

### ISSUE THREAD

**Issue by rgcv** [rgcv/es1617-adventures#50]
<a href="https://github.com/rgcv"><img src="https://avatars1.githubusercontent.com/u/4052080?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rgcv](https://github.com/rgcv)**
_Monday Apr 03, 2017 at 12:56 GMT_
_Originally opened as https://github.com/tecnico-softeng/es17al_01-project/issues/50_

----

Dependencies:

1. **Hotel** @vitiavas - done in 1df2354

- [x] #79: Make Hotel class persistent
- [x] #75: Make Hotel's fields persistent
- [x] #86: Implement relation between DomainRoot and Hotel

2. **Room** @vitiavas - done in 6870791

- [x] #81: Make Room class persistent
- [x] #78: Make Room's fields persistent
- [x] #89: Implement relation between Hotel and Room

3. **Booking** @vitiavas - done in 6870791, @gmsbaptista fixed in 303964f

- [x] #83: Make Booking class persistent
- [x] #76: Make Booking's fields persistent
- [x] #91: Implement relation between Room and Booking

@gmsbaptista tweaked in e3c3787

Various commits should be associated with this issue, one per "persistence advancement"
