### ISSUE TITLE
Implement test class ActivityPersistenceTest

### ISSUE THREAD

**Issue by rgcv** [rgcv/es1617-adventures#85]
<a href="https://github.com/schimini"><img src="https://avatars0.githubusercontent.com/u/10207527?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [schimini](https://github.com/schimini)**
_Monday Apr 03, 2017 at 14:00 GMT_
_Originally opened as https://github.com/tecnico-softeng/es17al_01-project/issues/85_

----

Dependencies:

1. **ActivityProvider** @rgcv - done in b0e5759

- [x] #57: Make ActivityProvider class persistent
- [x] #69: Make ActivityProvider's fields persistent
- [x] #92: Implement relation between DomainRoot and ActivityProvider

2. **Activity** @schimini - done in 4931b26

- [x] #55: Make Activity class persistent
- [x] #66: Make Activity's fields persistent
- [x] #84: Implement relation between ActivityProvider and Activity

3. **ActivityOffer** @schimini - done in 894b0e5

- [x] #56: Make ActivityOffer class persistent
- [x] #71: Make ActivityOffer's fields persistent
- [x] #88: Implement relation between Activity and ActivityOffer

4. **Booking** @rgcv - done in 36245c8

- [x] #58: Make Booking class persistent
- [x] #72: Make Booking's fields persistent
- [x] #90: Implement relation between ActivityOffer and Booking

Various commits should be associated with this issue, one per "persistence advancement"
